### ISSUE TITLE
Minor: Not very responsive layout when window height is only changed

### ISSUE THREAD

**Issue by Mortifera** [StraightOuttaCrompton/AVAMAE#5]
This seems to not be a vertical scrolling site so it would make sense to keep the footer at the bottom of the visible page and scale everything up.
E.g. at the moment for me, with the browser fullscreen on a 1080p monitor, the image text and the footer is below the bottom of the screen. 
And when I resize the page vertically it doesnt change layout. Now that isnt much of a problem typically but you may want to rescale the submit box and the image to keep all the content on the screen.

But at the very least I would make sure everything is visible fullscreen on a standard 1080p monitor.

**Comment by StraightOuttaCrompton** [comment]
I'm going to leave it as it is. I think it should be fine since http://www.foyles.co.uk/ does the same thing and it's a site built by AVAMAE.
