### ISSUE TITLE
Suggestion: Add an entry added successfully info box

### ISSUE THREAD

**Issue by Mortifera** [StraightOuttaCrompton/AVAMAE#6]
Users like confirmation that what they have done happened correctly.

Having a seperate page that said "Entry added successfully!" would work but if there is a usecase where many users need to be added then that would be tedious to return back to the main page.

I suggest instead that the text appear in a box on the main page, in green, if an entry was added successfully.

**Comment by StraightOuttaCrompton** [comment]
Not in spec
