### ISSUE TITLE
Not usable at 320 pixels width browser

### ISSUE THREAD

**Issue by Mortifera** [StraightOuttaCrompton/AVAMAE#7]
In chrome use the dev tools to make it easier to set window size. At 320 pixels width the text boxes go over the edge, and the text over the image is too large.

![image](https://user-images.githubusercontent.com/6323352/30299939-f1947c92-9749-11e7-9619-39bcefaf09ce.png)

**Comment by StraightOuttaCrompton** [comment]
This has now been fixed, I will close this issue when the form looks better in this view

**Comment by StraightOuttaCrompton** [comment]
Form now looks nice in this view!
